Numpy

In [1]:
# first of all we need to import numpy.

In [5]:
import numpy as np

In [6]:
# creating np array.

In [7]:
arr = np.array([1,2,3,4,5]) # 1D array

In [8]:
arr

array([1, 2, 3, 4, 5])

In [9]:
arr = np.array([[1,2,3,4] ,[5,6,7,8]]) # 2D array

In [10]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
# converting list into array

In [12]:
list1 = [1,2,3,4,5,6,7,8,9]

In [13]:
type(list1)

list

In [14]:
arr1 = np.array(list1)

In [15]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
type(arr1)

numpy.ndarray

In [17]:
# arange()

In [33]:
a = np.arange(5)

In [34]:
a

array([0, 1, 2, 3, 4])

In [35]:
a1 = np.arange(0,10) 

In [36]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
a2 = np.arange(0,10,2) # start-end-step

In [38]:
a2

array([0, 2, 4, 6, 8])

In [39]:
# zeros

In [40]:
b = np.zeros(10) #create a array of value zeros.But it is by default float.

In [41]:
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [44]:
b = np.zeros((5,5))

In [45]:
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [46]:
b1 = np.zeros(10, dtype=int) # for integer.

In [47]:
b1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [48]:
b1 = np.zeros((10,10),dtype=int) # 10 x 10 matrix

In [49]:
b1

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [50]:
# ones

In [51]:
c = np.ones(10) # now element value is 1

In [52]:
c

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [53]:
c = np.ones((5,5)) # 5x5 matrix dtype float.

In [54]:
c

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [55]:
c1 = np.ones(10,dtype=int) # change data type

In [56]:
c1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [57]:
c1 = np.ones((10,10),dtype=int)

In [58]:
c1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [59]:
# random,rand,randint.

In [60]:
r = np.random.rand(5) # generating 5 diff random no. but in float

In [61]:
r

array([0.7185825 , 0.92328269, 0.0124276 , 0.66921911, 0.96176153])

In [63]:
r = np.random.rand(5,6) # 5 x 6 matrix

In [64]:
r

array([[0.9179252 , 0.43717315, 0.41115114, 0.35872803, 0.5152995 ,
        0.17351494],
       [0.92730192, 0.11108429, 0.88451948, 0.98795354, 0.14926806,
        0.4590612 ],
       [0.45565922, 0.73455445, 0.69803034, 0.03431995, 0.87656505,
        0.97989136],
       [0.77823382, 0.87157767, 0.42784771, 0.59982108, 0.51173167,
        0.30572614],
       [0.02626809, 0.98320416, 0.3793626 , 0.20289052, 0.62991135,
        0.28159964]])

In [65]:
# for int no.

In [69]:
rint = np.random.randint(5) # generating random no. but less than 5 .

In [70]:
rint

1

In [73]:
rint1 = np.random.randint(0,10) # range between 0-10 . 10 not come.

In [74]:
rint1

6

In [88]:
rint2 = np.random.randint(0,10,5) # generating values between 0-10 and third argument for how many values.

In [89]:
rint2

array([9, 7, 1, 6, 3])

In [91]:
rintmatrix = np.random.randint(0,10,(5,2)) # 5 x 2 matrix --> 5-- rows , 2-- col.

In [92]:
rintmatrix

array([[3, 9],
       [2, 0],
       [3, 3],
       [5, 6],
       [1, 3]])